[package]
name = "jf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyjson = { git = "https://github.com/rhysd/tinyjson.git" }
# zstd = "0.12.4"
